### PR TITLE
Manual update to French translation and doc fixes

### PR DESCRIPTION
**Pull request by smCloudInTheSky**
Hi ! 

I've discovered recently (thanks to phoronix) this amazing tool ! 
I wanted to start contributing and since I'm french I wanted to start by looking at the french translation. It seemed incomplete so I'm opening already the MR to have an initial review of what I have done and then continue until I've at least done most of the lines. 

I've corrected some things that seemed incoherent with the english source.

### CODE REVIEW

**Comment by stgraber** [comment]
Thanks!

I haven't yet had the time to sort out the translation flow for Incus on Weblate but I'll do that hopefully later today and then upload your translations to the French language there.

After that you should be able to do further translations through Weblate directly which will then automatically flow into our releases.

**Comment by stgraber** [comment]
@smCloudInTheSky can you try accessing https://hosted.weblate.org/projects/incus/cli/ and see if you're able to translate Incus through it?

**Comment by smCloudInTheSky** [comment]
Yes it works ! So now I can continue on weblate and it will automatically be merged to the project ? 
If so I can drop my commit about translation and just keep the documentation part and add something about Weblate then ?

**Comment by smCloudInTheSky** [comment]
Would it be possible to merge my changes before ? Or do I have to redo all the modifications I did on the fr file ?

**Comment by stgraber** [comment]
I've done some minor commit message updates and this is now going through tests.
Once things look good, I'll merge it and Weblate will import the new changes, after that further updates can be done through Weblate.

**Comment by smCloudInTheSky** [comment]
Thanks ! 
I'll get some advice to continue from people who does translation as a job in the meantime !

**Pull request merged**
