### PR TITLE
Export QMP functions

### PR DESCRIPTION
**Pull request by bensmrs**
Closes: #1226

### CODE REVIEW

**Comment by stgraber** [comment]
@bensmrs I wonder, wouldn't it be cleaner if we just added a single command, `run_command` which would take one un-named argument (the command) and treat all kwargs as the arguments?

So we'd then have `run_qmp` that handles the raw JSON in/out QMP and `run_command` that lets you use a nicer syntax like:

```
run_command("qom-get", path="/machine/peripheral/dev-incus_root", property="serial")
```

I'm basically trying to avoid us having to duplicate the entire QMP command list in here.

**Comment by bensmrs** [comment]
I expected the remark but I agree with your last message, I’ll look at it tomorrow

**Comment by stgraber** [comment]
Thanks!

**Comment by bensmrs** [comment]
Just for a bit of context, I’m exploring the call stack to get the position in the Starlark code where there is a problem (in big scriptlets, it’s pretty useful). I haven’t found any other way, and Starlark doesn’t seem to offer much introspection into AST nodes, so that should do the trick…

**Review by stgraber — APPROVED** [review]

**Pull request merged**
