### PR TITLE
doc/installing: Add Rocky Linux 9

### PR DESCRIPTION
**Pull request by sspencerwire**

### CODE REVIEW

**Comment by sspencerwire** [comment]
@stgraber I see the "Signed-off-by" is still failing, but it *is* in the commit. :/

**Comment by stgraber** [comment]
Yeah, that's okay, I'll take a look and sort it out.

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Fixed formatting of the Author and Signed-off-By field, check is happy now.

**Comment by sspencerwire** [comment]
Thanks @stgraber

**Pull request merged**
