### PR TITLE
Add support for manual QMP configuration

### PR DESCRIPTION
**Pull request by bensmrs**
This PR allows to inject QMP commands at various stages of a VM initialization

### CODE REVIEW

**Comment by bensmrs** [comment]
HERE BE DRAGONS: if you set one of the keys to `"[0]"`, or basically any integer list, it makes Incus hang indefinitely. I think there is a problem with DigitalOcean’s QMP driver. We need to sanitize the input, but I haven’t had the courage to explore the problem in more detail.

**Comment by bensmrs** [comment]
I’m really not an expert in Go debugging, but Delve suggests that the QMP drivers hangs here: https://github.com/digitalocean/go-qemu/blob/2e3d0186973edb6a2811ee1240651bda63d7687d/qmp/socket.go#L250
Not sure what to do with that :)

**Comment by stgraber** [comment]
Static analysis test suggests you need to run `gofmt -s -w ./`

**Comment by bensmrs** [comment]
Sorry for all this noise, I’m slowly discovering the vast quantity of (yet unsuspected) checks

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Thanks, looks good!

I just did a bit of moving things around between commits, added an API extension for this and updated the project low-level keys to add those (and a couple we had missed).

**Pull request merged**
