### PR TITLE
Import LXD changes (last batch before the re-licensing)

### PR DESCRIPTION
**Pull request by stgraber**
Those are the remaining commits from the LXD repository prior to its re-licensing under the incompatible AGPLv3 license, no further changes will be imported from LXD.

### CODE REVIEW

**Review by hallyn — APPROVED** [review]

**Comment by TCB13** [comment]
So... Canonical decided to completely take over LXD and since it wasn't enough they also decided to kill Incus or any other fork that could benefit from Canonical's commits but be community driven. 

@stgraber what does this re-licensing mean for the future of this project?

**Comment by stgraber** [comment]
It just means we can't look at anything going into the LXD repository and so will have to duplicate work on fixing bugs or introducing features our users want.

That's mostly a waste of both projects' time and will cause the two to diverge faster than would have otherwise happened.

But it's not going to be the end of Incus, far from it. This latest move has attracted a fair amount of LXD users and contributors to jump ship and come to Incus instead. So if anything we're going to have a stronger project out of it.

**Comment by TCB13** [comment]
> But it's not going to be the end of Incus, far from it. This latest move has attracted a fair amount of LXD users and contributors to jump ship and come to Incus instead. So if anything we're going to have a stronger project out of it.

I'm all for jumping ship, no doubts there, better yet once Debian starts packing [Incus](https://wiki.debian.org/Incus), I guess around Debian 13.

With that said, yes, this is a waste of time, and more importantly financing. Canonical has big money to develop LXD and now I hope you and the other amazing people that will spend a TON of time improving Incus are properly funded / payed for their time.

Btw, only now I found your post about it. https://stgraber.org/2023/12/12/lxd-now-re-licensed-and-under-a-cla/

Thank you for all the great work.

**Comment by stgraber** [comment]
> With that said, yes, this is a waste of time, and more importantly funding. Canonical has big money to develop LXD and now I hope you and the other amazing people that will spend a TON of time improving Incus are properly funded / payed for their time.

Well, the LXD team is pretty well funded but a lot of those folks don't really work on LXD itself. These days there are only really 3 people working full time on LXD itself, the rest are part-time at best. Of those 3, 2 joined within the past 6 months so are still getting up to speed.

Whereas on our side, I'm working on it full-time and we have all the original LXD developers on the team as part-time maintainers. So which of the two is better staffed these days is up for debate ;)

**Pull request merged**
