### PR TITLE
Move `incusd init` to `incus admin init`

### PR DESCRIPTION
**Pull request by sharathsivakumar**
This change creates a new sub-command `admin` under `incus`. Further it moves `incusd init` to `incus admin init`

Check https://github.com/lxc/incus/issues/10 for more details

@stgraber Please review and let me know if fixes are needed.

TODO: Fix tests for change in command

### CODE REVIEW

**Comment by sharathsivakumar** [comment]
@stgraber I have left the init files under incusd as it is. Will remove them once all the tests pass for incus admin init

**Comment by stgraber** [comment]
@sharathsivakumar looking at the test results, you need a quick rebase at least and update after that as some packages have moved from shared/ to internal/ (cmd and i18n at least)

**Comment by sharathsivakumar** [comment]
Noted. The tests longer to complete and I forgot about it. I will rebase and check the issues.

**Comment by stgraber** [comment]
Still failing. Let me do the rebase for you see if that helps.

**Comment by stgraber** [comment]
So I ended up having to do:
 - Rebase on the current main branch
 - Update admin.go for new package paths
 - Applied all recent changes from incusd/main_init* to matching cmd/incus/admin_init*

It now builds fine, so lets see what the tests say.

**Comment by stgraber** [comment]
Some package rework is going to be needed to sort out the client builds (CGO_ENABLED=0) but those may be potentially tricky so I'll take care of those once the rest is happy.

**Comment by sharathsivakumar** [comment]
Thanks a ton. I will proceed with the remaining cmd changes.

**Comment by stgraber** [comment]
Hey there,

So I was thinking about the remaining commands. I don't think we'll actually move them all.
`activateifneeded` requires a lot of internal access and so should stay where it is.

As a summary, I think we'll want the following:
 - incus admin init
 - incus admin cluster
 - incus admin recover
 - incus admin sql
 - incus admin shutdown
 - incus admin waitready

**Comment by sharathsivakumar** [comment]
Cool. Let me start working on these and create PRs. I will create a PR for each one of the sub commands.

**Comment by sharathsivakumar** [comment]
@stgraber Shall I go ahead and delete the init related files under incusd? Maybe once all the test pass, I can do that before the merge?

**Comment by stgraber** [comment]
Yeah, you can add a commit that does that.

The current failures are mostly unrelated so it should be fine to do that now and then deal with anything else still using the old commands.

**Comment by sharathsivakumar** [comment]
@stgraber I started removing the redundant `incud/init.go` file and noticed that  the incusd api uses a function `initDataNodeApply` which was defined in `incusd/init.go`. So I see 2 options to resolve this:

- Define init.go as a shared package and use it in both the api and init commands. Do we have a location for shared internal packages?
- Leave the `incusd/init.go` as is. 

I think the first option is better in the long run. The second one is more of quick fix and does not help a lot.

What are your thoughts on this? Please feel free to suggest alternatives as well.
-

**Comment by stgraber** [comment]
Hmm, it may be possible to turn that function into something suitable for the `client/` package, I'll take a stab at that later today to see if I can unblock you. I'll also sort out the other package mess currently blocking the rest of the tests.

The old cluster join API isn't supported anymore so I think some of the code in those functions can go away, but not quite all of it sadly, so it's going to need a bunch of poking around across the codebase to sort that one out :)

If you have some time before I sort this one out, you may want to look at moving `recover` which hopefully will be a large-ish command but one that shouldn't be quite so tied to incusd internals.

**Comment by sharathsivakumar** [comment]
Cool. I will move on to recover. Feel free to let me know if I can help with the init restructuring. I will also try going through more of the code base and come up with some ideas to untangle it.

**Comment by stgraber** [comment]
I've sorted out the init.go thing, now I'm looking at the internal packages that are causing build failures on windows and macos.

**Comment by stgraber** [comment]
The big package cleanup has now been merged in main, I'm going to rebase this branch now.
I'll also add a commit which updates `test/*` to use `incus admin init` instead of `incusd init`

**Comment by stgraber** [comment]
And pushed, let's see how the tests do :)

**Comment by stgraber** [comment]
Ah, still need to get rid of an idmap import :)

**Comment by stgraber** [comment]
@sharathsivakumar all good!

**Comment by sharathsivakumar** [comment]
Wohoo. Thanks a ton! Will get the remaining things done!

**Pull request merged**
