### PR TITLE
Add `--alias` flag to `incus-simplestreams`

### PR DESCRIPTION
**Pull request by melato**
Add an --alias flag to the command *incus-simplestreams add*  See issue https://github.com/lxc/incus/issues/875

### CODE REVIEW

**Comment by stgraber** [comment]
Can you edit your commit to include the `Signed-off-by: Firstname Lastname <email>` line we require (see CONTRIBUTING.md).

From a usability standpoint, I think we should instead have:
 - `--no-default-alias` to turn off the default `distro/release/variant` alias
 - `--alias` to add aliases (can be passed multiple times)

**Comment by melato** [comment]
Ok, will submit a new pull request with --no-default-alias, and adding multiple aliases.
--no-default-alias will allow setting no alias at all.
There is an inconsistency with the "incus publish" command, which does not set a default alias.
*incus-simplestreams add* is another way of publishing.

By the way, why do some flag usages have "``" at the end?  For example, in cmd/incus/publish.go:
	cmd.Flags().StringArrayVar(&c.flagAliases, "alias", nil, i18n.G("New alias to define at target")+"``")
It does not show up in the usage.  Does it indicate something to spf13/cobra?

**Comment by stgraber** [comment]
> There is an inconsistency with the "incus publish" command, which does not set a default alias.
> _incus-simplestreams add_ is another way of publishing.

That's why, those are two different commands so them behaving differently doesn't really bother me. We'd probably have had `incus publish` also put in a default alias if we had known what we were publishing and if the native incus image store was capable of handling multiple images having the same alias.


> By the way, why do some flag usages have "`" at the end? For example, in cmd/incus/publish.go: cmd.Flags().StringArrayVar(&c.flagAliases, "alias", nil, i18n.G("New alias to define at target")+"`")

I don't recall exactly what issue that's working around other than it being a cobra behavior around default values which we didn't want and that this syntax makes it avoid.

**Comment by melato** [comment]
Closing this pull request.  I will create a new one.  I'm learning about pull requests and fork branches.

**Pull request closed without merging**
