### PR TITLE
incus/config_template: Add file support config template create

### PR DESCRIPTION
**Pull request by awalvie**
Part of #741

### CODE REVIEW

**Comment by stgraber** [comment]
This needs a rebase now :)

**Comment by awalvie** [comment]
Re-based it! Ready for review!

**Comment by awalvie** [comment]
> Example should be changed as input should be a template file (pongo) and so .tpl extension, not YAML

done!

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Static analysis failed because the translation commit doesn't match the code.

**Comment by awalvie** [comment]
> Static analysis failed because the translation commit doesn't match the code.

Sorry about that, have updated them!

**Comment by awalvie** [comment]
Force pushed to re-trigger the CI.

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Github looks pretty messed up right now. I've confirmed that this is all clean and ready to merge but the Github UI won't even let me merge this yet :)

I'll try again later.

**Comment by stgraber** [comment]
This needs a rebase now, hopefully Github can actually run the tests after that

**Pull request merged**
