### PR TITLE
Introduce `incus top`

### LINKED ISSUE #701: Add an `incus top` command
It would be nice to have an `incus top` command which accesses the metrics API (`/1.0/metrics`) and renders a list of instances with their CPU, memory and disk usage columns (similar to `top`).

That should all be possible with our existing APIs, so it's just CLI work to implement such a command and provide some hotkeys to switch the column sorting and refresh frequency.

### PR DESCRIPTION
**Pull request by CharanSriramUni**
Closes #701

### CODE REVIEW

**Comment by stgraber** [comment]
Looking into this one now

**Comment by CharanSriramUni** [comment]
Awesome; just added the updated translations as well.

**Comment by stgraber** [comment]
Did some simple fixes:
 - Rebased everything down to one commit
 - Added missing Signed-off-by line
 - Added missing bug reference
 - Generated translations
 - Ran `make static-analysis` and fixed what it found

After that looked at the logic itself and did:
 - Made all user visible strings translated
 - Made most errors in `handleKeystrokes` return out of the function to avoid infinite error loops

TODO:
 - Remove dependency on `internal/server/metrics`
 - Use the metrics as the source of instance names (save the GetInstanceNames call) which will also make stopped instances disappear

**Comment by CharanSriramUni** [comment]
@stgraber - Should be good now I think!

Removed the dependency and removed the extraneous call to `GetInstanceNames`. Also, reran translations and checked static-analysis. 

Thanks for all the help with this issue! Really made contributing to my first open source project a ton of fun :)

**Comment by stgraber** [comment]
Getting back to working on this one now.

**Comment by stgraber** [comment]
I did:
 - Rebase on main
 - Cleaned up commits
 - Ran `make static-analysis` and fixed what it reported
 - Changed to show absolute values instead of percentages
 - Changed sorting to show largest first

**Review by stgraber — APPROVED** [review]

**Comment by CharanSriramUni** [comment]
Do I need to worry about `Tests / System (1.21.x, cluster, dir) (pull_request) `? Seems to be a massive test from the logs but not sure if it's correct.

**Comment by stgraber** [comment]
Nope, that's fine, a random failure can happen every so often

**Pull request merged**
