### PR TITLE
Allow creating isolated OVN networks (no uplink)

### LINKED ISSUE #936: Allow creating isolated OVN networks (no uplink)
This came up in https://discuss.linuxcontainers.org/t/isolated-ovn-network/20167/6

While there are workarounds, it'd probably make sense to just support creating an OVN network with no `parent`, likely by introducing a special value of `none` (and consequently preventing a managed network be named `none`).

### PR DESCRIPTION
**Pull request by SpiffyEight77**
## Description

- feat: allow creating isolated OVN networks (no uplink)
- close #936 

## Details

- OS: Ubuntu 24.04
- Arch: x86_64

### Test result
```
root@playground:~/incus# incus network create ovn-none --type ovn network=none --debug
Network ovn-none created

root@playground:~/incus# incus network list
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
|    NAME    |   TYPE   | MANAGED |      IPV4       |           IPV6            | DESCRIPTION | USED BY |  STATE  |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| br-int     | bridge   | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| enp1s0     | physical | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| incusbr0   | bridge   | true    | 10.216.127.1/24 | fd42:fa48:9935:6601::1/64 |             | 1       | CREATED |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| lo         | loopback | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| lxcbr0     | bridge   | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| ovn-none   | ovn      | true    | 10.94.120.1/24  | fd42:d331:623f:c870::1/64 |             | 0       | CREATED |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| ovs-system | unknown  | false   |                 |                           |             | 0       |         |
+------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+


```

### CODE REVIEW

**Comment by SpiffyEight77** [comment]
After building from the source code and running tests, I found that the 'none' network isn't functioning correctly. 

I'll temporarily switch the PR to draft status.

**Comment by stgraber** [comment]
Thanks, I'm going to pull that one and take a look, see if I can get it over the finish line.

**Comment by stgraber** [comment]
Did a quick rebase on current main branch.

**Comment by stgraber** [comment]
So far I just did some basic rebasing and renaming of commits.

Next once I'm back on my desktop I'll push that logic to a test cluster so I can see what's going on with the addressing side of things and validate the rest of the logic.

Hopefully there isn't too much to it and I can sneak that one in just before tagging 6.4 :)

**Comment by stgraber** [comment]
Got it working. I managed to simplify a bit of the logic you had, I then had to add a bit more logic to handle the initial setup of the network which was failing and had to tweak the DHCPv4, DHCPv6 and RA code paths to just skip the DNS part. That was the issue you had with lacking DHCP.

I also had to add a bit of logic to the `nic` device to skip the uplink if it's "none" and lastly tweak the deletion logic so it doesn't fail due to missing router ports.

**Comment by stgraber** [comment]
Just waiting for doc and static analysis tests to complete, the rest isn't relevant as OVN tests happen separately through CI.

**Pull request merged**
