### PR TITLE
Add support for io.bus and io.cache for shared filesystems with VMs

### PR DESCRIPTION
**Pull request by SpiffyEight77**
## Description

- feat: add support for `io.bus` and `io.cache` for shared filesystems with VMs
- relates to #599

### CODE REVIEW

**Comment by stgraber** [comment]
Reviewing this one now.

**Comment by stgraber** [comment]
Summary of the changes I made to this:
 - Added the API extension commit
 - Separated the validation change into its own commit
 - Added more specific startup time validation to that commit
 - Re-worked the code a tiny bit to reduce the diff by moving the condition into the function
 - Split the io.cache from io.bus commit
 - Added a commit for the generated config metadata

**Review by stgraber — APPROVED** [review]

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Did some tests and had to fix:
 - Missing validation on `io.cache` for the new `metadata` value
 - Missing handling of disk without 9p in the QEMU driver

**Comment by SpiffyEight77** [comment]
Thank you so much; I learned a lot from this PR.

**Pull request merged**
