### PR TITLE
Bump OpenFGA to 0.3.1

### LINKED ISSUE #315: Builds from releases fail because of broken OpenFGA canonical imports
# Required information

 * Distribution: all
 * Distribution version: n/a
 * The output of "incus info" or if that fails:
  N/A

# Issue description

OpenFGA oauth2 package declares a canonical import for golang.org/x/oauth2, but the openfga/credentials package imports the code in their package namespace. Go's tooling correctly pulls in golang.org/x/oauth2 and ignores the openfga package. This causes incus builds to fail if dependencies are vendored.

issue: https://github.com/openfga/go-sdk/issues/63
PR: https://github.com/openfga/go-sdk/pull/64

# Steps to reproduce

 1. download released incus
 2. build
 3. observe failure

# Information to attach
See issue in COPR build here: https://github.com/ganto/copr-lxc4/issues/34

Note: this is an issue with a dependency, not Incus directly, but will require dependency updates when upstream is fixed.

### PR DESCRIPTION
**Pull request by stgraber**
Closes #315

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like @rhamzeh beat me to it with #316 :)

**Comment by rhamzeh** [comment]
Closed mine!

**Comment by bketelsen** [comment]
amazing.

**Comment by stgraber** [comment]
Looking into the test regression now

**Comment by stgraber** [comment]
Fixed an issue with mini-oidc, now to look at an issue with our OpenFGA driver.

**Review by hallyn — APPROVED** [review]

**Pull request merged**
