### PR TITLE
Add Rocky Linux to install

### PR DESCRIPTION
**Pull request by sspencerwire**
* add my `.markdownlint.yml` to `.gitignore` as perhaps not wanted in main project
* add "Rocky Linux 9" tab to `installing.md`

### CODE REVIEW

**Comment by sspencerwire** [comment]
At the end, removed the `.markdownlint.yml` file and `.gitignore` from the PR.

**Comment by stgraber** [comment]
@sspencerwire I believe the distros are meant to be alphabetically sorted, so Rocky should go later in the list

**Comment by sspencerwire** [comment]
> @sspencerwire I believe the distros are meant to be alphabetically sorted, so Rocky should go later in the list
That makes sense. I will change it. Thanks!

**Comment by sspencerwire** [comment]
> > @sspencerwire I believe the distros are meant to be alphabetically sorted, so Rocky should go later in the list
> > That makes sense. I will change it. Thanks!

@stgraber I've place Rocky after NixOS for alphabetical sorting. Let me know if there is anything else.  Thank you!

**Comment by stgraber** [comment]
Tiny fix needed:
```
.tmp/doc/installing.md:182: MD009 Trailing spaces
```

Also missing a `Signed-off-by` line in those two commits.

**Comment by sspencerwire** [comment]
> Tiny fix needed:
> 
> ```
> .tmp/doc/installing.md:182: MD009 Trailing spaces
> ```
> 
> Also missing a `Signed-off-by` line in those two commits.
I should have left my `.markdownlint.yml` file in my local. I'm not familiar with the `Signed-off-by` for the commit. I'm willing to learn though. Is it just `Signed-off-by` @sspencerwire ?  If so, I know I can fix it when I push back the removal of the spaces, but how can I fix the previously pushed commits? If I've missed a document I need to read to follow procedures here, let me know. And very sorry.

**Comment by stgraber** [comment]
CONTRIBUTING.md includes the syntax.
It's normally: `Signed-off-by: Firstname Lastname <email>`

As for fixing all the commits, easiest is to do `git rebase -i origin` and then use the `reword` keyword on all the commits. That will get you into a text editor where you can change the commits.

You'll need to `git push --force` after that.

**Comment by sspencerwire** [comment]
@stgraber Can I just close this and start over?  Seems easier than  trying to add the Signed-of-by to the older commits.

**Pull request closed without merging**
