### PR TITLE
Drop RBAC

### LINKED ISSUE #3: Remove Canonical RBAC support
Canonical RBAC is effectively a dead solution which shouldn't be brought forward into a fork.
Instead the fork will have OIDC and eventually OpenFGA support.

### PR DESCRIPTION
**Pull request by monstermunchkin**
Resolves #3

### CODE REVIEW

**Comment by metux** [comment]
Could you please give some explaination, what's this all about ?

**Comment by monstermunchkin** [comment]
> Could you please give some explaination, what's this all about ?

https://github.com/lxc/incus/issues/3

**Comment by monstermunchkin** [comment]
@stgraber does removing RBAC require an additional API extension? Or can we remove the `rbac` extension?

**Comment by stgraber** [comment]
We can do it without an API extension. We're going to be adding a generic "incus" API extension prior to the first release so those changes can all be detected in one shot.

What we probably should do as part of the PR is remove any API extension associated with RBAC so existing tools that detect support that way don't get confused.

**Comment by monstermunchkin** [comment]
@stgraber could you give this a quick review?

**Comment by stgraber** [comment]
@monstermunchkin will try to do later this evening!

**Review by stgraber — APPROVED** [review]
Looking good, thanks!

**Pull request merged**
